"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "development-only-change-me-before-production-0123456789abcdef",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = os.environ.get(
    "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,10.0.2.2"
).split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "simpleai",
    "accounts",
    "sermons",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.User"

CORS_ALLOWED_ORIGINS = os.environ.get(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173,capacitor://localhost,http://localhost",
).split(",")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
}
GOOGLE_OAUTH_CLIENT_IDS = tuple(
    value.strip()
    for value in os.environ.get("GOOGLE_OAUTH_CLIENT_IDS", "").split(",")
    if value.strip()
)
APPLE_OAUTH_CLIENT_IDS = tuple(
    value.strip()
    for value in os.environ.get("APPLE_OAUTH_CLIENT_IDS", "").split(",")
    if value.strip()
)

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_TASK_IGNORE_RESULT = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULE = {
    "recover-uploaded-sermons": {
        "task": "sermons.tasks.dispatch_uploaded_sermons",
        "schedule": 30.0,
    },
    "recover-processing-alerts": {
        "task": "sermons.tasks.dispatch_pending_processing_alerts",
        "schedule": 30.0,
    },
}

SERMON_PROCESSOR = os.environ.get(
    "SERMON_PROCESSOR",
    "sermons.provider_processor.ProviderSermonProcessor",
)
SERMON_PROCESSING_RETRY_DELAYS = (60, 5 * 60, 15 * 60)
PUSH_ALERT_SENDER = os.environ.get(
    "PUSH_ALERT_SENDER",
    (
        "sermons.push_alerts.LoggingPushAlertSender"
        if DEBUG
        else "sermons.push_alerts.NativePushAlertSender"
    ),
)
PUSH_ALERT_RETRY_DELAYS = (30, 2 * 60, 10 * 60, 30 * 60, 60 * 60)
PUSH_ALERT_TIMEOUT_SECONDS = float(os.environ.get("PUSH_ALERT_TIMEOUT_SECONDS", "15"))
APNS_KEY_ID = os.environ.get("APNS_KEY_ID", "")
APNS_TEAM_ID = os.environ.get("APNS_TEAM_ID", "")
APNS_AUTH_KEY_PATH = os.environ.get("APNS_AUTH_KEY_PATH", "")
APNS_TOPIC = os.environ.get("APNS_TOPIC", "com.pewcorder.app")
APNS_USE_SANDBOX = (
    os.environ.get(
        "APNS_USE_SANDBOX",
        "1" if DEBUG else "0",
    )
    == "1"
)
FCM_PROJECT_ID = os.environ.get("FCM_PROJECT_ID", "")
FCM_SERVICE_ACCOUNT_FILE = os.environ.get("FCM_SERVICE_ACCOUNT_FILE", "")
CHURCH_SUGGESTION_PROVIDER = os.environ.get(
    "CHURCH_SUGGESTION_PROVIDER",
    "sermons.church_suggestions.OverpassChurchSuggestionProvider",
)
OVERPASS_API_URL = os.environ.get(
    "OVERPASS_API_URL",
    "https://overpass-api.de/api/interpreter",
)
OVERPASS_USER_AGENT = os.environ.get(
    "OVERPASS_USER_AGENT",
    "Pewcorder/0.1 (contact: support@pewcorder.app)",
)
CHURCH_SUGGESTION_TIMEOUT_SECONDS = float(
    os.environ.get("CHURCH_SUGGESTION_TIMEOUT_SECONDS", "20")
)
CHURCH_SUGGESTION_LIMIT = int(os.environ.get("CHURCH_SUGGESTION_LIMIT", "5"))
SERMON_AUDIO_URL_MAX_AGE_SECONDS = int(
    os.environ.get("SERMON_AUDIO_URL_MAX_AGE_SECONDS", str(4 * 60 * 60))
)
PEWCORDER_PUBLIC_WEB_URL = os.environ.get(
    "PEWCORDER_PUBLIC_WEB_URL",
    "http://127.0.0.1:5173",
)
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.environ.get(
    "DJANGO_DEFAULT_FROM_EMAIL",
    "Pewcorder <share@pewcorder.app>",
)
EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("DJANGO_EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("DJANGO_EMAIL_USE_TLS", "1") == "1"
EMAIL_TIMEOUT = int(os.environ.get("DJANGO_EMAIL_TIMEOUT_SECONDS", "30"))

FFMPEG_BINARY = os.environ.get("FFMPEG_BINARY", "ffmpeg")
SERMON_TRANSCRIPTION_CHUNK_SECONDS = int(
    os.environ.get("SERMON_TRANSCRIPTION_CHUNK_SECONDS", "600")
)
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_TRANSCRIPTION_MODEL = os.environ.get(
    "OPENAI_TRANSCRIPTION_MODEL",
    "gpt-4o-transcribe-diarize",
)
OPENAI_TRANSCRIPTION_TIMEOUT_SECONDS = float(
    os.environ.get("OPENAI_TRANSCRIPTION_TIMEOUT_SECONDS", "900")
)
OPENAI_TRANSCRIPTION_REQUEST_RETRIES = int(
    os.environ.get("OPENAI_TRANSCRIPTION_REQUEST_RETRIES", "2")
)

SERMON_ARTIFACT_MODEL = os.environ.get("SERMON_ARTIFACT_MODEL", "openai")
SERMON_ARTIFACT_REASONING_LEVEL = os.environ.get(
    "SERMON_ARTIFACT_REASONING_LEVEL",
    "medium",
)
SIMPLEAI = {
    "defaults": ["openai"],
    "providers": {
        "openai": {
            "api_key": OPENAI_API_KEY,
            "default_model": os.environ.get("SIMPLEAI_OPENAI_MODEL", "gpt-5.5"),
        },
    },
    "logging": {
        "enabled": os.environ.get("SIMPLEAI_LOGGING", "0") == "1",
        "network_logging": False,
    },
}
