# Generated by Django 5.2.16 on 2026-07-20 23:22

import django.core.validators
import django.db.models.deletion
import sermons.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sermon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_draft_id", models.CharField(max_length=128)),
                ("captured_at", models.DateTimeField()),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(43200),
                        ]
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        max_length=500, upload_to=sermons.models.sermon_audio_path
                    ),
                ),
                ("audio_mime_type", models.CharField(max_length=120)),
                ("audio_size_bytes", models.PositiveBigIntegerField()),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sermons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-captured_at",),
                "indexes": [
                    models.Index(
                        fields=["owner", "processing_status"],
                        name="sermons_ser_owner_i_a54bc8_idx",
                    ),
                    models.Index(
                        fields=["owner", "captured_at"],
                        name="sermons_ser_owner_i_9eb9a7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "source_draft_id"),
                        name="unique_owner_source_draft",
                    )
                ],
            },
        ),
    ]
