# Generated by Django 5.2.16 on 2026-07-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="processing_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sermon",
            name="processing_claim_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sermon",
            name="processing_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sermon",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
