# Generated by Django 5.2.16 on 2026-07-20 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0002_sermon_processing_attempts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "sermon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="transcript",
                        serialize=False,
                        to="sermons.sermon",
                    ),
                ),
                ("text", models.TextField()),
                ("segments", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScriptureReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book", models.CharField(max_length=64)),
                ("chapter_start", models.PositiveSmallIntegerField()),
                (
                    "verse_start",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "chapter_end",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("verse_end", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "sermon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scripture_references",
                        to="sermons.sermon",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="RelatedSermon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "related_sermon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_for_sermons",
                        to="sermons.sermon",
                    ),
                ),
                (
                    "sermon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_sermons",
                        to="sermons.sermon",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sermon", "related_sermon"),
                        name="unique_related_sermon_suggestion",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sermon", models.F("related_sermon")), _negated=True
                        ),
                        name="related_sermon_cannot_reference_itself",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudyArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("short_summary", "Short summary"),
                            ("long_summary", "Long summary"),
                            ("outline", "Outline"),
                            (
                                "adult_discussion_questions",
                                "Adult discussion questions",
                            ),
                            ("kids_discussion_questions", "Kids discussion questions"),
                        ],
                        max_length=40,
                    ),
                ),
                ("content", models.TextField()),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sermon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_artifacts",
                        to="sermons.sermon",
                    ),
                ),
            ],
            options={
                "ordering": ("kind",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sermon", "kind"),
                        name="unique_sermon_study_artifact_kind",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TagSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("normalized_name", models.CharField(max_length=80)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "sermon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_suggestions",
                        to="sermons.sermon",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sermon", "normalized_name"),
                        name="unique_sermon_tag_suggestion",
                    )
                ],
            },
        ),
    ]
