# Generated by Django 5.2.16 on 2026-07-21 00:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0003_transcript_scripturereference_relatedsermon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reflection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sermon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflections",
                        to="sermons.sermon",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
