# Generated by Django 5.2.16 on 2026-07-21 00:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0005_sharelink"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="liturgical_day",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="sermon",
            name="occasion_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sunday", "Sunday"),
                    ("feast", "Feast"),
                    ("wedding", "Wedding"),
                    ("funeral", "Funeral"),
                    ("midweek", "Midweek"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Church",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("normalized_name", models.CharField(editable=False, max_length=160)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "normalized_address",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="churches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name", "address"),
            },
        ),
        migrations.AddField(
            model_name="sermon",
            name="church",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sermons",
                to="sermons.church",
            ),
        ),
        migrations.CreateModel(
            name="Preacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("normalized_name", models.CharField(editable=False, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preachers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="sermon",
            name="preacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sermons",
                to="sermons.preacher",
            ),
        ),
        migrations.AddConstraint(
            model_name="church",
            constraint=models.UniqueConstraint(
                fields=("owner", "normalized_name", "normalized_address"),
                name="unique_owner_church_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="preacher",
            constraint=models.UniqueConstraint(
                fields=("owner", "normalized_name"),
                name="unique_owner_preacher_identity",
            ),
        ),
    ]
