# Generated by Django 5.2.16 on 2026-07-21 00:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_deviceregistration"),
        ("sermons", "0006_sermon_liturgical_day_sermon_occasion_kind_church_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[("ready", "Ready"), ("failed", "Failed")],
                        max_length=16,
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivering", "Delivering"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("delivery_attempts", models.PositiveSmallIntegerField(default=0)),
                ("delivery_error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_alerts",
                        to="accounts.deviceregistration",
                    ),
                ),
                (
                    "sermon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_alerts",
                        to="sermons.sermon",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["delivery_status", "updated_at"],
                        name="sermons_pro_deliver_270819_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sermon", "device", "processing_status"),
                        name="unique_sermon_device_processing_alert",
                    )
                ],
            },
        ),
    ]
