# Generated by Django 5.2.16 on 2026-07-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_deviceregistration"),
        ("sermons", "0007_processingalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingalert",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="processingalert",
            index=models.Index(
                fields=["delivery_status", "next_attempt_at"],
                name="sermons_pro_deliver_570d82_idx",
            ),
        ),
    ]
