# Generated by Django 5.2.16 on 2026-07-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0008_processingalert_next_attempt_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyartifact",
            name="kind",
            field=models.CharField(
                choices=[
                    ("short_summary", "Short summary"),
                    ("long_summary", "Long summary"),
                    ("outline", "Outline"),
                    ("practical_next_steps", "Practical next steps"),
                    ("call_to_action", "One next action"),
                    ("adult_discussion_questions", "Adult discussion questions"),
                    ("kids_discussion_questions", "Kids discussion questions"),
                ],
                max_length=40,
            ),
        ),
    ]
