# Generated by Django 5.2.16 on 2026-07-24 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0013_transcript_raw_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='consider_end_seconds',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sermon',
            name='consider_start_seconds',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
