# Generated by Django 5.2.16 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0015_sermon_audio_normalized_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="audio_isolated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
