# Generated by Django 5.2.16 on 2026-07-26

import sermons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0016_sermon_audio_isolated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="playback_audio",
            field=models.FileField(
                blank=True,
                max_length=500,
                upload_to=sermons.models.sermon_playback_audio_path,
            ),
        ),
        migrations.AddField(
            model_name="sermon",
            name="playback_audio_mime_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sermon",
            name="playback_audio_size_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
