# Generated by Django 5.2.16 on 2026-08-02 23:16

import sermons.models
from django.db import migrations, models


def separate_legacy_isolated_audio(apps, schema_editor):
    Sermon = apps.get_model("sermons", "Sermon")
    legacy_isolated = Sermon.objects.filter(
        audio_isolated_at__isnull=False,
    ).exclude(playback_audio="")
    legacy_isolated.filter(transcription_audio_source="playback").update(
        transcription_audio_source="isolated",
    )
    # Preserve the existing storage reference as the isolated variant. Clearing
    # the normalized marker lets the backfill command create a fresh playback
    # copy directly from the original without recopying large media in migration.
    legacy_isolated.update(
        isolated_audio=models.F("playback_audio"),
        isolated_audio_mime_type=models.F("playback_audio_mime_type"),
        isolated_audio_size_bytes=models.F("playback_audio_size_bytes"),
        playback_audio="",
        playback_audio_mime_type="",
        playback_audio_size_bytes=None,
        audio_normalized_at=None,
    )


def restore_legacy_combined_audio(apps, schema_editor):
    Sermon = apps.get_model("sermons", "Sermon")
    separated = Sermon.objects.filter(
        audio_isolated_at__isnull=False,
        playback_audio="",
    ).exclude(isolated_audio="")
    separated.filter(transcription_audio_source="isolated").update(
        transcription_audio_source="playback",
    )
    separated.update(
        playback_audio=models.F("isolated_audio"),
        playback_audio_mime_type=models.F("isolated_audio_mime_type"),
        playback_audio_size_bytes=models.F("isolated_audio_size_bytes"),
        audio_normalized_at=models.F("audio_isolated_at"),
        isolated_audio="",
        isolated_audio_mime_type="",
        isolated_audio_size_bytes=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0022_sermon_capture_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="isolated_audio",
            field=models.FileField(
                blank=True,
                max_length=500,
                upload_to=sermons.models.sermon_isolated_audio_path,
            ),
        ),
        migrations.AddField(
            model_name="sermon",
            name="isolated_audio_mime_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sermon",
            name="isolated_audio_size_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            separate_legacy_isolated_audio,
            restore_legacy_combined_audio,
        ),
        migrations.AlterField(
            model_name="sermon",
            name="transcription_audio_source",
            field=models.CharField(
                choices=[
                    ("playback", "Normalized playback"),
                    ("isolated", "Isolated playback"),
                    ("original", "Original upload"),
                ],
                default="original",
                max_length=20,
            ),
        ),
    ]
